apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: mayukh-workloads  # Replace with your namespace
spec:
  containers:
  - name: debug-container
    image: curlimages/curl:latest  # This image contains curl
    command: ["sleep", "infinity"]  # Keep the pod running

    resources:                      
      requests:                     
        memory: "64Mi"              
        cpu: "250m"                 
      limits:                       
        memory: "128Mi"             
        cpu: "500m" 