# This is an example of the one the most basic 
# template for a Pod
apiVersion: v1                        # Version of the API
kind: Pod                             # Type of resource

metadata:                             # All the metadata about the Pod
  name: mayukh-nginx-pod              ## name of the pod
  namespace: mayukh-workloads         ## The namespace where the Pod will be present
  labels:                             ## Key-Val pairs that are called labels
    run: mayukh-nginx-pod
spec:                                 # Details about the containers in Pod
  containers:                         # We can give multiple containers
    - name: nginx                     ## Name of the first container
      image: nginx                    ## Image that is used for the first container
      imagePullPolicy: IfNotPresent   ## When should you pull the image from regisrty
      resources: {}                   ## Host resource limits for the container while running (CPU,RAM)
  
  dnsPolicy: ClusterFirst             # DNS to be used
  restartPolicy: Always               # What to do if pod dies!
status: {}                            # Used to indicate the status of the Pod
