apiVersion: v1                        
kind: Pod                             

metadata:                             
  name: mayukh-nginx-pod-complete          
  namespace: mayukh-workloads         
  labels:                             
    run: mayukh-nginx-pod
spec:                                 
  containers:                         
    - name: nginx                     
      image: nginx:latest                    
      # imagePullPolicy: IfNotPresent
      command: ["printenv"]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
      ports:
      - containerPort: 80
        hostPort: 8080
        
      resources:                      
        requests:                     
          memory: "64Mi"              
          cpu: "250m"                 
        limits:                       
          memory: "128Mi"             
          cpu: "500m"                 
  
  dnsPolicy: ClusterFirst             
  restartPolicy: OnFailure                          
